apworld: https://github.com/SerpentAI/Archipelago/releases/download/kmk-0002/keymasters_keep.apworld

game_repos:
  - https://github.com/SerpentAI/KeymastersKeepGameArchive # This is the archived repo for pre-1.0 games. A bunch of them will be replaced by repos later in this list.
  - https://github.com/BowserCrusher/BowserKeymastersKeepGames
  - https://github.com/CaptainMcGee/McGeeKeymastersKeepGames
  - https://github.com/delcake/KeymastersKeepGames
  - https://github.com/ManNamedGarbo/KeymastersKeepGames
  - https://github.com/MediocreNightmare/GarfaxKeep
  - https://github.com/Knuxfan24/KnuxKeep
  - https://github.com/mathstar/KeymastersKeepGames
  - https://github.com/pamymaf/KeymastersKeepGames
  - https://github.com/Pantscada/keymasterskeepgames
  - https://github.com/ansem5/keymasters-keep-games
  - https://github.com/Rooby-Roo/KeymastersKeepGameArchive
  - https://github.com/RaceProUK/WestsideKeep
  - https://github.com/Seatori/KeymastersKeepGames
  - https://github.com/SerpentAI/KeymastersKeepGames
  - https://github.com/silasary/SilasaryKeep
  - https://github.com/Silvris/KeymastersKeepGames
  - https://github.com/Sundia1908/KeymastersKeepGames
  - https://github.com/deyoungbryce/KeymastersKeepGames
  - https://github.com/Venumii/KeymastersKeepGames

