name: Test apworld
on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Bundler
        run: |
          python bundler.py

      - uses: Eijebong/ap-actions/ap-tests@main
        with:
          apworld-path: keymasters_keep
          ap-version: '0.6.1'
          python-version: '3.12'
          checkout: 'false'
